openapi: 3.0.2
info:
    title: MyRestApi
    version: 0.0.1


paths:
    /sync:
        post:
            summary: Sync invoke
            operationId: sync
            responses:
                200:
                    description: ok
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                  message:
                                    type: string

            x-amazon-apigateway-integration: 
                httpMethod: POST
                type: aws_proxy
                uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Sync.Arn}/invocations
    /async:
        post:
            summary: Async invoke
            operationId: async
            parameters:
                - name: type
                  in: query
                  description: query string
                  required: false
                  schema:
                      type: string
            responses:
                200:
                    description: ok
            x-amazon-apigateway-integration: 
                httpMethod: POST
                type: aws
                uri:
                    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Async.Arn}/invocations
                requestTemplates: 
                    application/json: |
                        {
                            "queryStringParameters": {
                                "type": "$input.params('type')"
                            },
                            "context": {
                                "authorizer": {
                                    "claims": "$context.authorizer.claims"
                                }
                            }
                        }    
                responses:
                    default: 
                        statusCode: 200
                requestParameters:         
                    integration.request.header.X-Amz-Invocation-Type: "'Event'"
                    integration.request.querystring.type: method.request.querystring.type
                passthroughBehavior: "when_no_match"
                contentHandling: "CONVERT_TO_TEXT"