version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "poc-apigateway-async"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zsi2sdnq9c94"
s3_prefix = "poc-apigateway-async"
confirm_changeset = false
